[package]
name = "learing-axum-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {version="0.6.18", features = ["headers"]}
serde = {version="1.0.160", features = ["derive"]}
serde_json = "1.0.96"
tokio = {version="1.28.0", features = ["full"]}
tracing = "0.1.37"
tracing-subscriber = {version="0.3.17", features=["env-filter"]}
tower-http = {version="0.4.0", features = ["cors"]}
sqlx = {version="0.6.3", features = ["runtime-tokio-rustls", "postgres", "json"]}
dotenv = "0.15.0"
config = "0.13.1"
